---
- name: Update Apt-Cache
  apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  loop:
    - unzip

- name: Ensure group exists
  group:
    name: "{{ newrelic_java_agent_group }}"

- name: Ensure user exists
  user:
    name: "{{ newrelic_java_agent_user }}"

- name: Check if file exists
  stat:
    path: "{{ newrelic_java_agent_parent_path }}"
  register: parent_dir

- name: Create New Relic Parent Directory
  file:
    path: "{{ newrelic_java_agent_parent_path }}"
    state: directory
    owner: "{{ newrelic_java_agent_user }}"
    group: "{{ newrelic_java_agent_group }}"
  when: parent_dir.stat.exists == false

- name: Download the latest java agent .zip and unarchive it into NR Agent dir
  unarchive:
    remote_src: yes
    dest: "{{ newrelic_java_agent_parent_path }}"
    creates: "{{ newrelic_java_agent_path }}"
    src: "{{ newrelic_java_agent_url }}"
    owner: "{{ newrelic_java_agent_user }}"
    group: "{{ newrelic_java_agent_group }}"

- name: Stat the New Relic Custom file
  stat:
    path: "{{ newrelic_java_agent_path }}/newrelic.yml"
  register: custom_file

- debug: var="custom_file" verbosity=3

- name: Place newrelic.yml config (default)
  template:
    src: "newrelic.yml.j2"
    dest: "{{ newrelic_java_agent_path }}/newrelic.yml"
    owner: "{{ newrelic_java_agent_user }}"
    group: "{{ newrelic_java_agent_group }}"
  when: 
    - newrelic_java_agent_custom_config is not defined
    - not custom_file.stat.exists

- name: Place newrelic.yml config (custom)
  template:
    src: "{{ newrelic_java_agent_custom_config }}"
    dest: "{{ newrelic_java_agent_path }}/newrelic.yml"
    owner: "{{ newrelic_java_agent_user }}"
    group: "{{ newrelic_java_agent_group }}"
  when: 
    - newrelic_java_agent_custom_config is defined
  
- name: Update ownership of NR agent dir + contents
  file:
    path: "{{ newrelic_java_agent_parent_path }}"
    owner: "{{ newrelic_java_agent_user }}"
    group: "{{ newrelic_java_agent_group }}"
    state: directory
    recurse: yes